---
title: "Valorant Web Scrape"
output: html_document
date: "2022-09-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Valorant Setups/Settings

```{r}
library(tidyverse)
library(rvest)
library(sqldf)
library(RSelenium)
```

Valorant w/ Rselenium
```{r}

url = "https://prosettings.net/valorant-pro-settings-gear-list/"

driver <- RSelenium::rsDriver(browser = "chrome", port = 4882L,
                              chromever =
                                system2(command = "wmic",
                                        args = 'datafile where name="C:\\\\Program Files (x86)\\\\Google\\\\Chrome\\\\Application\\\\chrome.exe" get Version /value',
                                        stdout = TRUE,
                                        stderr = TRUE) %>%
                                stringr::str_extract(pattern = "(?<=Version=)\\d+\\.\\d+\\.\\d+\\.") %>%
                                magrittr::extract(!is.na(.)) %>%
                                stringr::str_replace_all(pattern = "\\.",
                                                         replacement = "\\\\.") %>%
                                paste0("^",  .) %>%
                                stringr::str_subset(string =
                                                      binman::list_versions(appname = "chromedriver") %>%
                                                      dplyr::last()) %>%
                                as.numeric_version() %>%
                                max() %>%
                                as.character())
remote_driver = driver[["client"]]
remote_driver$navigate(url)

#driver$server$stop()
#gc()

table = remote_driver$findElement(using = "id", value = "table_1")
val_table = read_html(table$getElementAttribute('innerHTML')[[1]]) %>% html_nodes("tbody")%>%html_table
valorant_table = val_table[[1]]

colnames(valorant_table) = c("Team", "Name", "Mouse","HZ","DPI","Sensitivity","eDPI","Scoped Sensitivity","Monitor","Moniter HZ", "GPU", "Resolution","Mousepad","Keyboard","Headset")

#write_csv(valorant_table, "C:\\Users\\XxadrionixX\\Desktop\\R Projects\\Data-Projects-R-Projects\\valorant_table.csv")
```
`r valorant_table`


Using Valorant Settings/Setups data
```{r}
#valorant_table = read_csv('valorant_table.csv')
#maybe GROUPBY and basic descriptive analysis in R
sapply(valorant_table, class)     #checking which classes are correct
valorant_table$HZ = str_replace(valorant_table$HZ,",","")     #clean data to change it to numeric
col_num = c("HZ", "DPI", "eDPI")    #clean col name
valorant_table[col_num] = sapply(valorant_table[col_num], as.double)
sapply(valorant_table, class)     #changed col names
#NEED TO GET RID OF ALL ROWS WITH NA
#NEED TO GET RID OF ALL ROWS WITH NA
#NEED TO GET RID OF ALL ROWS WITH NA
#NEED TO GET RID OF ALL ROWS WITH NA

#Settings only, no external peripherals
sqldf("SELECT Team, avg(DPI) as 'Average Team DPI', avg(Sensitivity) as 'Average Team Sens.', avg(eDPI) as 'Average Team DPI', avg('Scoped Sensitivity') as 'Average Team Scoped Sens.'
      FROM valorant_table
      GROUP BY Team")

pairs(valorant_table[lapply(valorant_table, class) == "numeric"])

tapply(valorant_table$eDPI, valorant_table$Team, mean)
mean(valorant_table$HZ[is.na(valorant_table$HZ)==FALSE])

#How Sensitivity follows DPI
DPI_Sens = lm(DPI ~ Sensitivity, data = valorant_table)
plot(valorant_table$Sensitivity, valorant_table$DPI)
  abline(DPI_Sens[1], DPI_Sens$coefficients[2])

DPI_ScopedSens = lm(DPI ~ `Scoped Sensitivity`, data = valorant_table)
plot(valorant_table$`Scoped Sensitivity`, valorant_table$DPI)
  abline(DPI_ScopedSens$coefficients[1], DPI_ScopedSens$coefficients[2])


```
